---
xpack.security.enabled: false
node.attr.box_type: hot
node.name: "elasticsearch-01"
cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.type: zen
discovery.zen.minimum_master_nodes: 2
#discovery.zen.ping.unicast.hosts: ["elasticsearch:9300","elasticsearch-02:9302"]
discovery.zen.ping.unicast.hosts: ["elasticsearch:9300","elasticsearch-02:9302","elasticsearch-03:9303"]
